name: MurderMystery
main: cn.lanink.murdermystery.MurderMystery
version: "1.0.0"
api:
  - 1.0.0
load: POSTWORLD
author: lt_name
loadbefore:
  - EconomyAPI
  - ScoreboardPlugin

permissions:
  MurderMystery.all:
    default: true
  MurderMystery.op:
    default: op