name: MurderMystery
main: cn.lanink.murdermystery.MurderMystery
version: "${pom.version}"
api:
  - 1.0.0
load: POSTWORLD
author: "lt_name"
loadbefore:
  - EconomyAPI
  - Tips

permissions:
  MurderMystery.all:
    default: true
  MurderMystery.op:
    default: op